version: 0.0
os: linux
files:
  - source: /
	destination: /var/www/html/
hooks:
  AfterInstall:
	- location: script/change.sh
  	runas: root
  	timeout: 300
ApplicationStart:
  - location: script/apachestart.sh
	runas: rootsc
	timeout: 600
